# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='username',
            field=models.TextField(default='Carter', max_length=24),
            preserve_default=False,
        ),
    ]
